### ISSUE TITLE
Why does negative_captions append negative_traj twice？

### ISSUE THREAD

**Issue by 1021331023** [airbert-vln/airbert#10]
https://github.com/airbert-vln/airbert/blob/88d88f2075bafa5e1fe4dd1a98f5b04a1011162e/utils/dataset/bnb_dataset.py#L218-L230

There are two similar code blocks.

One is to define **negative_captions** and append negative_traj into **negative_captions**, the other is to define **negative_images** but still append negative_traj into **negative_captions**.

Why does negative_captions append negative_traj twice? Is this designed? Thanks.

**Comment by guhur** [comment]
Thanks for reporting it. 
The code is misleading but the mining process generates only negative captions.
I think generating negative images did not work well.
