### ISSUE TITLE
QUESTIONS WHEN REPRODUCING THE RESULT

### ISSUE THREAD

**Issue by 1021331023** [airbert-vln/airbert#11]
Hi, I have several questions when I reproduce the results as follows.

1. Is row 2 in Table 6 the result tested from the model [airbert_r2rRSA](https://drive.google.com/uc?id=1WL6ENeLRMFndpbx1LTNrpnSgYBH2lcO2)?

2. How to combine speaker and follower with airbert in row 5 of Table 6 ( i.e. airbert ensembled of speaker and follower models)? I did not find any relevant codes in your project.

3. What is the use of add_exploration_path  in test.py? https://github.com/airbert-vln/airbert/blob/4a744c262ed4381e9a752905f8fe0e64c867c2ae/test.py#L139 While it becomes True,  the result file will include "exploration_path" and results in an error when submitted to the leaderboard. https://github.com/airbert-vln/airbert/blob/4a744c262ed4381e9a752905f8fe0e64c867c2ae/test.py#L173-L176 While it becomes False, we can successfully submit the result to the leaderboard, and the measured spl is normal (0.6696), not as low as 0.01 as mentioned in the paper. Could you explain that?

4. Moreover, what is the model that you submitted to the leaderboard which got an OS 0.99 and spl 0.01, could you provide it?

Thanks for your attention!

**Comment by guhur** [comment]
1. Nope. It has been fine-tuned with speaker generated data + the shuffling loss. So it corresponds to Row 7, Table 3.
2. The script I used was pretty this one: https://github.com/arjunmajum/vln-bert/blob/master/scripts/grid-search.py
3. `add_exploration_path` means that you penalize the robot for all candidate trajectories. It is used for the leaderboard (providing hence a very low SPL and very high OSR), but it provides very little insight on the quality of the selected trajectory. Hence, when evaluating the agent, this parameter should be equal to False. I don't know why it results in an error when submitting to the leaderboard, but I'll let you fix it to avoid filling my submission trials.
4. The model submitted on the leaderboard is airbert_r2rRSA combines to a speaker, a follower and to VLN-BERT, as indicated in the footnote 5.
