### ISSUE TITLE
I cannot download data/beamsearch/aug_beams_train.json.

### ISSUE THREAD

**Issue by liangcici** [airbert-vln/airbert#2]
It shows 403 error.
Could you please check the link https://drive.google.com/uc?id=1ukpTRI6LelEl0_gk10azW_Td95XANL2e ?

**Comment by guhur** [comment]
Hi, 
Sorry for the issue. I updated the link:  https://drive.google.com/uc?id=1GqvSRSZvvYKQaM4nGYZYR-3VPWgbbU9N

**Comment by guhur** [comment]
Fix! It was just a permission issue.
