### ISSUE TITLE
Evaluation with given pre-trained airbert model R2R

### ISSUE THREAD

**Issue by meera1hahn** [airbert-vln/airbert#3]
Can you give instructions on how to do evaluation with the given airbertR2R models. Currently running into bugs in the code when trying to do inference.

Note: I am trying to run evaluation with the following command 
```
python test.py \
--split val_unseen \
--from_pretrained airbert_r2rRS.bin \
--save_name airbert
```

Errors:
1) class VLNOSCAR(OscarPreTrainedModel) --> OscarPreTrainedModel doesnt exist
2) using AutoTokenizer not BertTokenizer in test.py
3) config.model_name doesnt exist
4) key error on pad_packed(output[0].squeeze(1), opt_mask)

**Comment by guhur** [comment]
Hi,

I am sorry for the troubles, and I thank you for noticing me on the multiple issues you have encountered. 

I have updated the code and checked that is working fine with me. Also, I added instructions on the README.
