### ISSUE TITLE
Can you provide with instruction generation model?

### ISSUE THREAD

**Issue by JeremyLinky** [airbert-vln/airbert#4]
Hello, I'm curious about the setting that uses generated instruction, which adopts ViLBERT and is trained to generate captions for single BnB image-caption pairs. Can you provide the scripts and trained model? Thanks.

**Comment by guhur** [comment]
Hi, sorry I don't have the code anymore, but it is quite trivial to implement. Results were quite disappointing though. I think you could look at more recent papers such as Visual-Language Navigation Pretraining via Prompt-based Environmental Self-exploration (Liang et al.).
