### ISSUE TITLE
Is the VIL-BERT pretrained model really fit for training?

### ISSUE THREAD

**Issue by JeremyLinky** [airbert-vln/airbert#6]
Hi there, when I tried to train airbert with concatnate captions in 3.1, I got the following infos printed:

![image](https://user-images.githubusercontent.com/50053052/162623045-1c400ed9-9c29-4768-99db-c619932f3380.png)

which shows that the some weights of Airbert not initialized from pretrained model. Is this normal? Thanks.

**Comment by guhur** [comment]
That's OK.
