### ISSUE TITLE
How can I train the airbert with multi-gpus？

### ISSUE THREAD

**Issue by JeremyLinky** [airbert-vln/airbert#7]
I found that when training airbert, there was always only one GPU in use, and then it always reported a memory overflow error, even though I lowered the batch size many times (one GPU on my machine has about 12GB of memory). I'm wondering how much memory I need to train and if I can distribute training across multiple GPUs? Thanks.

**Comment by guhur** [comment]
I worked on V100 GPUs. See codes here for DDP: https://github.com/airbert-vln/airbert/tree/main/slurm
