### ISSUE TITLE
There was no "action" output while I was training the Airbert with  Concatenation setting.

### ISSUE THREAD

**Issue by JeremyLinky** [airbert-vln/airbert#8]
Hi there, When I was training the Airbert with  Concatenation setting, something went wrong and it came from the following code:
https://github.com/airbert-vln/airbert/blob/88d88f2075bafa5e1fe4dd1a98f5b04a1011162e/train.py#L641

which means that there was no "action" output while I was training the Airbert with  Concatenation setting, could you explain that? Thanks

**Comment by guhur** [comment]
Thanks for reporting it! It was a big the name should have been 'ranking'. I just fixed it
